load("//tensorboard/defs:web.bzl", "tf_web_library")

package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])

tf_web_library(
    name = "roboto",
    srcs = [
        "roboto.html",
    ],
    path = "/tf-imports",
    deps = [
        "@com_google_fonts_roboto",
    ],
)

tf_web_library(
    name = "inter",
    srcs = [
        "inter.html",
    ],
    path = "/tf-imports",
    deps = [
        "@com_google_fonts_inter",
    ],
)

tf_web_library(
    name = "ibm_plex_mono",
    srcs = [
        "ibm_plex_mono.html",
    ],
    path = "/tf-imports",
    deps = [
        "@com_google_fonts_ibm_plex_mono",
    ],
)
