load("//tensorbored/defs:defs.bzl", "tf_ng_module")

package(default_visibility = ["//tensorbored:internal"])

tf_ng_module(
    name = "runs_legacy",
    srcs = [
        "runs_module.ts",
    ],
    deps = [
        "//tensorbored/webapp/runs_legacy/views/legacy_runs_selector",
        "@npm//@angular/core",
    ],
)
