# This is a stub BUILD file that remains after the deletion of the experimental
# data frame API. We keep it (temporarily) to allow copybara imports to succeed.
package(default_visibility = ["//tensorbored:internal"])

licenses(["notice"])

exports_files(["LICENSE"])
